### ISSUE TITLE
Can't Make Intent

### ISSUE THREAD

**Issue by Blackwood416** [gujjwal00/avnc#110]
I wanted to make an Activity Intent to AVNC's home activity in my bash script for termux.
But I got an error. Here are the command and the error info.
`am start -n com.gaurav.avnc/com.gaurav.avnc.ui.home.HomeActivity`

> Starting: Intent { cmp=com.gaurav.avnc/.ui.home.HomeActivity }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.termux.termuxam.IActivityManager.startActivityAsUser(IActivityManager.java:165)
        at com.termux.termuxam.Am.runStart(Am.java:635)
        at com.termux.termuxam.Am.onRun(Am.java:353)
        at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.termux.termuxam.Am.main(Am.java:74)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:427)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.gaurav.avnc/.ui.home.HomeActivity } from null (pid=11122, uid=10361) not exported from uid 10441
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at android.app.IActivityManager$Stub$Proxy.startActivityAsUser(IActivityManager.java:8489)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1076)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1071)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:717)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1156)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1128)

It seems that it is a AVNC's bug.

**Comment by gujjwal00** [comment]
Yes, you can't launch `HomeActivity` directly. AVNC uses activity aliases for external sources.
See [this](https://github.com/gujjwal00/avnc/blob/4ffce9d1cb72cd53e4d08e6055c577fdeccc8dd7/app/src/main/AndroidManifest.xml#L25-L33) & [this](https://github.com/gujjwal00/avnc/blob/master/app/src/main/java/com/gaurav/avnc/ui/home/SplashActivity.kt) to learn more about how this is setup (and some reasoning behind this).

So to launch home activity, please run: `am start -n com.gaurav.avnc/com.gaurav.avnc.StartupActivity`

Also note that AVNC supports `vnc://` URIs. If you simply want to launch a connection, you can directly use this. Let me know if you need any help.

**Comment by Blackwood416** [comment]
@gujjwal00 It worked! Thanks for your help.

**Comment by TyraVex** [comment]
Hello,
I am able to launch a startup activity using `am start -n com.gaurav.avnc/.StartupActivity` and a vnc URI using `am start -n com.gaurav.avnc/.UriReceiverActivity -a android.intent.action.VIEW -d vnc://127.0.0.1:5900`, but I can't find a way to launch a specific session profile, which is linked to all the parameters I need for this specific session. Can someone help me with this issue?
Thanks

**Comment by TyraVex** [comment]
For more context, here is the intent I am trying to access:
```
intent={dat=Localhost flg=0x10000000 cmp=com.gaurav.avnc/.ui.vnc.VncActivity}
```

**Comment by gujjwal00** [comment]
Hi @TyraVex , please see https://github.com/gujjwal00/avnc/issues/162#issuecomment-1520052991.

You should be able to do something like this:

 ```
am start -n com.gaurav.avnc/.UriReceiverActivity -a android.intent.action.VIEW -d vnc://?ConnectionName=abcd
```

**Comment by TyraVex** [comment]
> Hi @TyraVex , please see [#162 (comment)](https://github.com/gujjwal00/avnc/issues/162#issuecomment-1520052991).
> 
> You should be able to do something like this:
> 
> ```
> am start -n com.gaurav.avnc/.UriReceiverActivity -a android.intent.action.VIEW -d vnc://?ConnectionName=abcd
> ```

That works! Thank you so much!
