### ISSUE TITLE
Not working with wayvnc

### ISSUE THREAD

**Issue by danielphan2003** [gujjwal00/avnc#54]
I'm currently using wayvnc (latest commit) with sway (v1.6-ish), and I can only access it via bVNC, but not AVNC.

Edit: note that I'm also using Tailscale to access it remotely, though I don't think that connecting via a VPN like this would cause any issue.

**Comment by gujjwal00** [comment]
Can you please copy the logs from **Settings -> Tools -> Logs**, and paste them here?

Try to connect once more before copying the logs, so that the error is visible in logs. 

Connecting via VPN should not cause any problem.

**Comment by danielphan2003** [comment]
Sure, here it is:
```
--------- beginning of main
02-06 11:02:48.072  3659  3680 D OpenGLRenderer: endAllActiveAnimators on 0xb40000769cb80500 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000769f240460
02-06 11:02:49.225  3659  3680 D OpenGLRenderer: endAllActiveAnimators on 0xb40000769c9e3500 (RippleDrawable) with handle 0xb40000769f1442a0
02-06 11:02:49.225  3659  3680 D OpenGLRenderer: endAllActiveAnimators on 0xb40000769c9b1900 (RippleDrawable) with handle 0xb400007718e7ae20
02-06 11:02:49.900  3659  3686 I NativeVnc: VNC server supports protocol version 3.8 (viewer 3.8)
02-06 11:02:49.964  3659  3686 I NativeVnc: We have 1 security types to read
02-06 11:02:49.964  3659  3686 I NativeVnc: 0) Received security type 19
02-06 11:02:49.964  3659  3686 I NativeVnc: Selecting security type 19 (0/1 in the list)
02-06 11:02:49.964  3659  3686 I NativeVnc: Selected Security Scheme 19
02-06 11:02:50.017  3659  3686 I NativeVnc: Got VeNCrypt version 0.2 from server.
02-06 11:02:50.198  3659  3686 I NativeVnc: We have 1 security types to read
02-06 11:02:50.198  3659  3686 I NativeVnc: 0) Received security type 262
02-06 11:02:50.198  3659  3686 I NativeVnc: Selecting security type 262 (0/1 in the list)
02-06 11:02:50.210  3659  3680 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076aa22e200 (MaterialCardView) with handle 0xb400007718e7ae20
02-06 11:02:50.264  3659  3686 E NativeVnc: Unsupported credential type requested
02-06 11:02:50.264  3659  3686 I NativeVnc: Reading credential failed
02-06 11:02:50.264  3659  3686 E NativeVnc: errnoToStr: (11 Try again)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: Connection failed
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: java.io.IOException: 
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:65)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:6)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-06 11:02:50.264  3659  3686 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
02-06 11:02:52.299  3659  3680 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076aa046500 (RippleDrawable) with handle 0xb40000769f23b000
````

**Comment by gujjwal00** [comment]
The security type `264` used by wayvnc (it uses x509 certificates) is not currently supported by AVNC. 

You could enable alternative security types in wayvnc (e.g. username & password), if possible.

You can also try disabling authentication in wayvnc configuration, and use SSH tunnel for securing the connection.

**Comment by danielphan2003** [comment]
Well, since I don't open port 5901 to the public and use an encrypted VPN instead, disabling auth in wayvnc could work since Tailscale already handles the auth part. I will try it out later.

**Comment by danielphan2003** [comment]
Can confirm it works on wayvnc without auth.

**Comment by thiswillbeyourgithub** [comment]
Reporting that I can't connect to my server using a VPN but I can if I disable it. I get no error message, just the "circular arrow" that doesn't move for up to a minute.
When I turn the VPN off it works instantly.

The option "disable connection without the VPN" being turned off in both cases.
I am using ssh tunneling also.

What kind of information might be useful from me to troubleshoot the issue?

**Comment by gujjwal00** [comment]
Hi @thiswillbeyourgithub , after connection failure, you can copy the logs from **Settings ➡ Tools ➡ Logs** and paste them here.

PS: If your problem is not specific to wayvnc, its better to open a separate issue.
