### ISSUE TITLE
AVNC crashes with certain devices

### ISSUE THREAD

**Issue by user8446** [gujjwal00/avnc#81]
Hi,

 I have noticed that AVNC does not work and crashes on an ASUS tablet running Android 7 which has a MediaTek processor.

I traced the crash back to the ConnectBot SSH lib specifically this issue: https://github.com/connectbot/connectbot/issues/814

I'm not sure if there's anything that you can do on your end or not and I'm also opening this issue so others can find it as well.

**Comment by gujjwal00** [comment]
Thanks for letting me know. I don't know if its possible to disable certain algorithms in sshlib, but let me look more into this.

**Comment by gujjwal00** [comment]
Hi  @user8446, can you please test this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/8812691/app-debug.zip)

It disables Curve25519 for key exchange. If the APK works and this use-case is important for you, I can add this behind an experimental preference.

**Comment by user8446** [comment]
Ok I tried the debug version and even with the ed25519 key still in place, it connected the first time. Every attempt after fails for some reason. I tried clearing data & reinstalling the app. I also tried switching to an RSA key but it still fails. Double checked the keys, server, and a different client and all is well. Here is the AVNC client log:

```
--------- beginning of main
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: Connection failed
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: java.io.IOException: There was a problem while connecting to [10.9.8.100:22](http://10.9.8.100:22/)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.Connection.connect(Connection.java:808)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.Connection.connect(Connection.java:590)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.SshTunnel.open(SshTunnel.kt:95)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel.connect(VncViewModel.kt:217)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:66)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:188)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:152)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:156)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.Connection.connect(Connection.java:760)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	... 11 more
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: Caused by: java.io.IOException: Hostkey signature sent by remote is wrong!
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:718)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:614)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:310)
06-02 21:55:52.551  6783  6799 E ReceiverCoroutine: 	at java.lang.Thread.run(Thread.java:761)
```
