### ISSUE TITLE
can not connect to realnvc server

### ISSUE THREAD

**Issue by yan1990y** [gujjwal00/avnc#93]
my server runs realvnc server 6.1.0,authentication is "vnc password",avnc can not connect to it, app show authentication failed

**Comment by gujjwal00** [comment]
Can you please copy the logs from `Settings > Tools > Logs` and paste here?

Also, please double check the password saved in AVNC.

**Comment by yan1990y** [comment]
![bd8bd4d8e127b3216060f13cac6eda70](https://user-images.githubusercontent.com/31801069/187654907-6e564891-c384-4189-aa63-14c02b165196.jpg)
![25e6db72de97d2532d2ad829a1818308](https://user-images.githubusercontent.com/31801069/187654918-702e4448-0b45-4d19-aeb7-a49c2018a7d3.jpg)
Log is empty,I had checked my password in realvnc viewer for android app.

**Comment by gujjwal00** [comment]
Can you use ADB to retrieve the logs?
Let me know if you need help with ADB.

**Comment by yan1990y** [comment]
I can use adb.But I need you to tell me detail,so I can do it.I know how to use android studio to read logs,but I don't know how to find specified app log

**Comment by gujjwal00** [comment]
> I know how to use android studio to read logs,but I don't know how to find specified app log

Great! Don't worry about specific app, just copy everything. 
- Clear/delete all logs using Android Studio
- Try to connect in AVNC
- Copy the logs

**Comment by yan1990y** [comment]
2022-09-01 11:21:30.977 10332-10355/com.gaurav.avnc I/NativeVnc: VNC server supports protocol version 5.0 (viewer 3.8)
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: We have 5 security types to read
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: 0) Received security type 13
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: 1) Received security type 133
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: 2) Received security type 5
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: 3) Received security type 129
2022-09-01 11:21:30.982 10332-10355/com.gaurav.avnc I/NativeVnc: 4) Received security type 192
2022-09-01 11:21:30.983 10332-10355/com.gaurav.avnc I/NativeVnc: Unknown authentication scheme from VNC server: 13, 133, 5, 129, 192
2022-09-01 11:21:30.983 10332-10355/com.gaurav.avnc E/ReceiverCoroutine: Connection failed
    java.io.IOException: Authentication failed
        at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
        at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:65)
        at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
2022-09-01 11:21:31.134 10332-10332/com.gaurav.avnc D/CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10022; state: ENABLED
2022-09-01 11:21:31.387 10332-10350/com.gaurav.avnc D/OpenGLRenderer: endAllActiveAnimators on 0x79be48ac40 (MaterialCardView) with handle 0x78ce47c180
2022-09-01 11:21:49.919 10332-10355/com.gaurav.avnc I/NativeVnc: VNC server supports protocol version 5.0 (viewer 3.8)
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: We have 5 security types to read
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: 0) Received security type 13
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: 1) Received security type 133
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: 2) Received security type 5
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: 3) Received security type 129
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: 4) Received security type 192
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: Unknown authentication scheme from VNC server: 13, 133, 5, 129, 192
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc E/ReceiverCoroutine: Connection failed
    java.io.IOException: Authentication failed
        at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
        at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:65)
        at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
2022-09-01 11:21:50.332 10332-10350/com.gaurav.avnc D/OpenGLRenderer: endAllActiveAnimators on 0x79be48ac40 (MaterialCardView) with handle 0x78ce479120

**Comment by yan1990y** [comment]
this vnc server config:
![企业微信截图_1662002637520](https://user-images.githubusercontent.com/31801069/187825248-c07334fa-8ab5-489d-96d8-a1642e97d556.png)

**Comment by gujjwal00** [comment]
Thanks for the logs & server config. As you can see, none of the security types offered by server is currently supported by AVNC:

```
2022-09-01 11:21:49.923 10332-10355/com.gaurav.avnc I/NativeVnc: Unknown authentication scheme from VNC server: 13, 133, 5, 129, 192
```
  
This is due to current server configuration you have: 

![image](https://user-images.githubusercontent.com/27951674/187827259-d950e9eb-dad3-4e15-b2f5-e8a3090d7407.png)

Can you please try changing Encryption to `Prefer on`, and Authentication to `VNC password`?

**Comment by yan1990y** [comment]
after my test,I change Encryption to Prefer on,anvc works.always on option will fail.change Authentication to VNC password or keep Windows password have no difference.

**Comment by gujjwal00** [comment]
Yes, `Always on` forces an encrypted connection, but RealVNC's encryption scheme is not supported by the LibVNCClient library (which is used by AVNC).  `Prefer on` allows unencrypted connection, which will be used by AVNC.

If you want encrypted connections with a RealVNC server, you can use SSH tunneling.

**Comment by yan1990y** [comment]
thanks a lot!
