### ISSUE TITLE
Doesn't work with the default Raspberry PI VNC server

### ISSUE THREAD

**Issue by cClaude** [gujjwal00/avnc#97]
I would like to reopen https://github.com/gujjwal00/avnc/issues/7

On `Raspberry Pi OS`  it possible to enable VNC support using `sudo raspi-config`

This install following file: `realvnc-vnc-server_6.10.1.47571_arm64.deb` for `realvnc-vnc-server (6.10.1.47571)`.

I managed to get AVNC to work with my raspberries (it was working before summer 2022).

I have tested with versions available on f-droid:

* Version 1.9.1 (13) 
* Version 1.9.2 (14)
* Version 2.0.0 (15) 

Here is my logs (using last version):

``` 
--------- beginning of perf
11-16 16:34:13.063 32725 12201 I 110     :  OptJank - total:81 frameGap:87 delta#0#49#7#41#0#32
--------- beginning of main
11-16 16:40:32.185  2833  2833 D ViewRootImpl[PrefsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
11-16 16:40:32.251  2833  2833 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@31aee6f[HomeActivity]
11-16 16:40:32.252  2833  2833 D ViewRootImpl[HomeActivity]: windowFocusChanged hasFocus=true inTouchMode=true
11-16 16:40:33.237  2833  2833 I com.gaurav.avn: failed to find target package for overlay /system/product/overlay/ProductOverlay-oneplus-framework-res.apk
11-16 16:40:33.237  2833  2833 I com.gaurav.avn: failed to find target package for overlay /system/system_ext/overlay/CommonOverlay-oneplus-framework-res.apk
11-16 16:40:33.237  2833  2833 I com.gaurav.avn: failed to find target package for overlay /odm/overlay/OdmOverlay-oneplus-framework-res.apk
--------- beginning of system
11-16 16:40:33.257  2833  2833 D ViewRootImpl: support adaptive color gamut feature!
11-16 16:40:33.260  2833  2833 D ViewRootImpl[HomeActivity]: windowFocusChanged hasFocus=false inTouchMode=true
11-16 16:40:33.261  2833  2833 D OpScreenModeManager: setRefreshRate parent androidx.drawerlayout.widget.DrawerLayout{3411868 GFE...... ......I. 0,0-0,0 #7f0900a5 app:id/drawer_layout} parent width 0 parent height 0 mRatio 1.2
11-16 16:40:33.261  2833  2833 D OpScreenModeManager: setRefreshRate view com.gaurav.avnc.ui.vnc.FrameView{9b5bf8b VFE...... ......I. 0,0-0,0 #7f0900cc app:id/frame_view} viewRate 0 width 0 height 0
11-16 16:40:33.274  2833  2833 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
11-16 16:40:33.283  2833  2833 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@fb1df6b[VncActivity]
11-16 16:40:33.284  2833  2833 D ViewRootImpl[VncActivity]: windowFocusChanged hasFocus=true inTouchMode=true
11-16 16:40:43.302  2833 12638 E NativeVnc: ConnectClientToTcpAddr6: connect
11-16 16:40:43.302  2833 12638 I NativeVnc: Unable to connect to VNC server
11-16 16:40:43.302  2833 12638 E NativeVnc: errnoToStr: (115 Operation now in progress)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: Connection failed
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: java.io.IOException: 
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:62)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:8)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
11-16 16:40:43.303  2833 12638 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
11-16 16:41:04.422  2833 12639 E NativeVnc: ConnectClientToTcpAddr6: connect
11-16 16:41:04.422  2833 12639 I NativeVnc: Unable to connect to VNC server
11-16 16:41:04.422  2833 12639 E NativeVnc: errnoToStr: (115 Operation now in progress)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: Connection failed
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: java.io.IOException: 
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:62)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:8)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
11-16 16:41:04.423  2833 12639 E ReceiverCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
11-16 16:41:12.751  2833  2833 D ViewRootImpl[VncActivity]: windowFocusChanged hasFocus=false inTouchMode=true
11-16 16:41:12.766  2833  2833 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@31aee6f[HomeActivity]
11-16 16:41:12.767  2833  2833 D ViewRootImpl[HomeActivity]: windowFocusChanged hasFocus=true inTouchMode=true
11-16 16:41:13.174  2833  2833 D OpScreenModeManager: setRefreshRate parent androidx.drawerlayout.widget.DrawerLayout{3411868 GFE...... ......I. 0,0-0,0 #7f0900a5 app:id/drawer_layout} parent width 0 parent height 0 mRatio 1.2
11-16 16:41:13.175  2833  2833 D OpScreenModeManager: setRefreshRate view com.gaurav.avnc.ui.vnc.FrameView{9b5bf8b VFE...... ......I. 0,0-0,0 #7f0900cc app:id/frame_view} viewRate 0 width 0 height 0
11-16 16:41:15.830  2833  2833 E com.gaurav.avn: Invalid ID 0x00000000.
11-16 16:41:15.834  2833  2833 D ViewRootImpl: support adaptive color gamut feature!
11-16 16:41:15.839  2833  2833 D ViewRootImpl[HomeActivity]: windowFocusChanged hasFocus=false inTouchMode=true
11-16 16:41:15.865  2833  2833 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
11-16 16:41:15.889  2833  2833 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@30f8ac4[PrefsActivity]
11-16 16:41:15.891  2833  2833 D ViewRootImpl[PrefsActivity]: windowFocusChanged hasFocus=true inTouchMode=true

```

**Comment by gujjwal00** [comment]
From the logs, it looks like in your case AVNC is not even able to connect to Raspberry PI. Can you please double check the host address & port number, and that the PI is reachable from your Android device?

**Comment by gujjwal00** [comment]
No problem 👍.

I too have forgotten about my firewall rules more than once.
